version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing compatible npm..."
        - npm install -g npm@9
        - echo "Installing project dependencies..."
        - rm -rf node_modules package-lock.json
        - npm install

  build:
    commands:
      - echo "Building the React app..."
      - npm run build

  post_build:
    commands:
      - echo "Build completed successfully."
      - echo "Syncing build output to S3..."
      - aws s3 sync build/ s3://chatroom-frontend-s3/ --delete

artifacts:
  files:
    - '**/*'
  base-directory: build
